from models import *

db.session.add(User(username='sapan',name='Sapan', email='sapan@seil.cse.iitb.ac.in', occupancy_status='absent'))
db.session.add(User(username='shinjan',name='Shinjan', email='shinjan@seil.cse.iitb.ac.in', occupancy_status='absent'))
db.session.add(User(username='anshul',name='Anshul', email='anshul@seil.cse.iitb.ac.in', occupancy_status='absent'))
db.session.add(User(username='gowri',name='Gowri', email='gowri@seil.cse.iitb.ac.in', occupancy_status='absent'))
db.session.add(User(username='bhushan',name='Bhushan', email='bhushan@seil.cse.iitb.ac.in', occupancy_status='absent'))
db.session.add(User(username='chaitra',name='Chaitra', email='chaitra@seil.cse.iitb.ac.in', occupancy_status='absent'))
db.session.add(User(username='adithya',name='Adithya', email='adithya@seil.cse.iitb.ac.in', occupancy_status='absent'))
db.session.add(User(username='mahesh',name='Mahesh', email='mahesh@seil.cse.iitb.ac.in', occupancy_status='absent'))
db.session.add(User(username='nivethitha',name='Nivethitha', email='nivethitha@seil.cse.iitb.ac.in', occupancy_status='absent'))
db.session.add(User(username='ankit',name='Ankit', email='ankit@seil.cse.iitb.ac.in', occupancy_status='absent'))
db.session.add(User(username='suchitra',name='Suchitra', email='suchitra@seil.cse.iitb.ac.in', occupancy_status='absent'))
db.session.add(User(username='akshay',name='Akshay', email='akshay@seil.cse.iitb.ac.in', occupancy_status='absent'))
db.session.add(User(username='santhos',name='Santhos', email='santhos@seil.cse.iitb.ac.in', occupancy_status='absent'))
db.session.commit()